name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node: [18]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Cache .pnpm-store & .cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            ~/.cargo/registry
            ~/.cargo/git
            assembly-rust/target

          key: ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/Cargo.toml') }}

      - run: pnpm i
      - run: pnpm run wasm
      - run: pnpm run build:docs

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
