name: github pages

on:
  push:

jobs:
  deploy:
    strategy:
      matrix:
        os: ["ubuntu-20.04"]
        node: [16]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache .pnpm-store & .cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            ~/.cargo/registry
            ~/.cargo/git
            assembly-rust/target

          key: ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6

      - run: pnpm i
      - run: pnpm run wasm
      - run: pnpm run build:docs

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
